### ISSUE TITLE
Feature Request: Secure WebSockets and Authentication

### ISSUE THREAD

**Issue by aycanirican** [valderman/haste-compiler#137]
There is no way to protect server side calls from rest of the world.

**Comment by valderman** [comment]
As long as the server you're talking to supports secure WebSockets, Haste does too: simply use a `wss://` URL rather than a `ws://` one when connecting. Haste.App supports secure sockets as of [this commit](https://github.com/valderman/haste-app/commit/5ac0cc81de57b1762acfb2dbe820c795a14d80ec).
