### ISSUE TITLE
Feature Request: Nix Expression for haste-compiler.

### ISSUE THREAD

**Issue by aycanirican** [valderman/haste-compiler#204]
It seems that installing haste-compiler via nix may solve lot's of dependency and installation problems.

**Comment by llelf** [comment]
BTW I see the same
```
hastec: target ‘dist/build/GHC/Classes.dyn_o’ is not a module name or a source file
```
both with 0.4.4 and HEAD [ghc 7.8.3 on mac].
Feature⟶bug?

**Comment by obadz** [comment]
I think https://github.com/NixOS/nixpkgs/commit/7f2163fc97d422bf19f71f09f4c813e49b1fcc8e should more or less close this issue
