### ISSUE TITLE
Unsupported PrimOp: mkWeakNoFinalizer# ,  Unsupported PrimOp: deRefWeak#

### ISSUE THREAD

**Issue by arianvp** [valderman/haste-compiler#210]
When you install elerea as a dependency to a project you get warned that these two PrimOps are unspported : `mkWeakNoFinalizer#` and `deRefWeak#` . indeed when you run an application that uses elerea you also get the error  `Uncaught Unsupported PrimOp: mkWeakNoFinalizer# `

example application that triggers the crash:

    import Data.IORef
    import Control.Monad
    import FRP.Elerea.Simple

    main = do
      smp <- start $ do
        ref <- execute $ newIORef 0
        effectful $ do
          x <- readIORef ref
          putStrLn "Count: " ++ show x
          writeIORef ref $! x+1
          return ()
      replicateM_ 5 smp

**Comment by arianvp** [comment]
I'll check if this fixes my code today.

**Comment by valderman** [comment]
Assuming this to be fixed: the primops are there and there are no further reports of problems.
