### ISSUE TITLE
Road to sandboxing

### ISSUE THREAD

**Issue by adinapoli** [valderman/haste-compiler#223]
Hello Anton!

This ticket is a way to gather all the "todo" in order to get proper sandbox integration in Haste.

At the moment, what prevents me from using Haste in production is the lack of sandboxing for reproducible builds. The sandboxing panorama is split in half:

- There is the official cabal sandbox, used by the majority of people
- There is the "full fat" sandboxing solution, for example hsenv.

At work we use "hub", which is a sort of hybrid approach between the two, but the idea is still that you have two package dbs: one from your local Haskell installation and one for your current sandbox which ships only the "delta packages". The core packages (base, integer-gmp, array, etc) are always coming from the global installation, at least from my experience.

There would be two places were I would like to work starting : 
- The "haste-boot" process seems a bit hairy. On my machine, running macosx and using hub as a sandbox, "haste-boot" works when pulling stuff from internet (via the "online" installation) but fails if I try to do a local one. I think this could be fixed to some extend using proper package-db during the installation.
- The "haste-inst" reference the global package-db, making impossible for me, at the current state of things, to use haste in production, because what I would like to have is haste to reference my local sandbox to be able to track precisely the dependencies of my projects.

How much work would be involved on this? I'm very happy to help, under proper mentoring.
Do you think we are looking at a big fat chunk of work or we are not far away from it?

Thanks,
Alfredo

**Comment by valderman** [comment]
Fixed on master; sandboxing seems to work flawlessly with the new `haste-cabal`.
