### ISSUE TITLE
Support FFI imports à la GHCJS

### ISSUE THREAD

**Issue by redneb** [valderman/haste-compiler#242]
GHCJS supports imports like the following:

```haskell
foreign import javascript unsafe "document.write($1+'<br/>');" writeNumber :: Int -> IO ()
```

In haste it is possible to do something similar with `haste-ffi-parser`. The problem is that `haste-ffi-parser` adds an extra compilation step. It would be nice if something like that was integrated into the haste compiler.

**Comment by valderman** [comment]
Closing as fixed; as of 0.5, Haste.Foreign provides equivalent functionality.
