### ISSUE TITLE
broken packages in haste-inst

### ISSUE THREAD

**Issue by ts468** [valderman/haste-compiler#247]
Hi,

it seems as packages that are installed with haste-boot are marked as broken. In particular, Cabal is missing dependencies. It seems as not all package IDs are set during the boot process.
Could a second boot stage solve that problem by recompiling all packages?

In case a second boot stage should prove useful, it would be great if the current and the second boot stage would be executable independently. That could help with integrating Haste into a distribution like e.g. NixOS.

Also, I would prefer if haste-inst would be called cabal-haste, or maybe also haste-cabal. It would make the analogy between GHC and Haste much clearer.

**Comment by valderman** [comment]
This is fixed on master; `haste-inst` is now `haste-cabal`, and broken packages are no longer present in the package database.
