### ISSUE TITLE
Cabal conflict on `integer-gmp`

### ISSUE THREAD

**Issue by danse** [valderman/haste-compiler#263]
Hi there, i wanted to try Haste today but `haste-boot` failed with the following error:

```
Resolving dependencies...
cabal: constraints conflict: we have the top level constraint integer-gmp
==0.5.0.0, but
integer-gmp-0.5.0.0 was excluded because of the top level constraint
'integer-gmp installed' which means that only installed instances of the
package may be selected.
Command '/Users/francesco/experiments/haste/.hsenv/cabal/bin/haste-inst' failed with error  code 1
```

This is a bit weird because i am trying in an Haskell virtual environment, created with `hsenv`, and the only command i run after activating the environment is `cabal install haste-compiler`. So i just have dependencies required by `haste-compiler`, if `hsenv` is working properly.

The installed version of `haste-compiler` is 0.4.3

**Comment by danse** [comment]
thanks for the kind and detailed explanation! i have GHC version `7.8.3`, and integer-gmp version `0.5.1.0` under the folder you mentioned. I am trying to set up an Hsenv with GHC `7.6.3` as you said and i am having troubles with that, but this is not related to the Haste compiler anymore. So is Haste supposed to be used just with GHC `7.6.3`? I can't find this in the README

**Comment by valderman** [comment]
Is this issue still present in master? Package handling has had a major overhaul, so this is most likely fixed.

**Comment by danse** [comment]
This issue is pretty old, so i guess that it does not make much sense to try to troubleshoot that error anymore. Nowadays i would not use `hsenv` for an installation, but i would rather use Cabal sandboxes or Stack. Anyway, i tried to install `haste-compiler` from master in an Hsenv sandbox, and the error i get has completely a different nature:

    Failed to download http://valderman.github.io/haste-libs/haste-libs-0.5.1.0.tar.bz2: Not Found 

I would say to close this issue

**Comment by valderman** [comment]
@danse, that looks like a symptom of trying to boot Haste from git without `--local`. Are you sure it's related to hsenv?

Either way, thanks for taking the time to check this out! If someone *really* needs to use hsenv over sandboxes and can't get it to work, they'll have to reopen this.
