### ISSUE TITLE
lifted-base can not be installed because of cabal library version

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [valderman/haste-compiler#28]
When I try to install lifted-base (it is a dependency) with haste-inst, I get:

    Resolving dependencies...
    In order, the following will be installed:
    lifted-base-0.2 (reinstall)
    Warning: Note that reinstalls are always dangerous. Continuing anyway...
    cabal: Error: some packages failed to install:
    lifted-base-0.2 failed during the configure step. The exception was:
    user error (The package requires Cabal library version -any && >=1.9.2 but no
    suitable version is installed.)

**Comment by valderman** [comment]
Fixed on master by the new `haste-cabal`.
