### ISSUE TITLE
haste-boot on Linux fails (building latest)

### ISSUE THREAD

**Issue by mbrodersen** [valderman/haste-compiler#282]
I have been using haste for quite a while now and it is most excellent!

However I today updated haste-compiler to latest:

$ (git update haste-compiler folder)
$ cabal update
$ cabal install
$ haste-boot --force --local

and the haste-boot command => the following install error (to do with containers-0.5.6.2):

Building data-default-instances-dlist-0.0.1...
Installed data-default-instances-dlist-0.0.1
Failed to install containers-0.5.6.2
Build log ( /home/morten/.cabal/logs/containers-0.5.6.2.log ):
Configuring containers-0.5.6.2...
Building containers-0.5.6.2...
Preprocessing library containers-0.5.6.2...
Stack space overflow: current size 8388608 bytes.
Use `+RTS -Ksize -RTS' to increase it.
cabal: Error: some packages failed to install:
containers-0.5.6.2 failed during the building phase. The exception was:
ExitFailure 2
data-default-0.5.3 depends on containers-0.5.6.2 which failed to install.
data-default-instances-containers-0.0.1 depends on containers-0.5.6.2 which
failed to install.
haste-lib-0.5 depends on containers-0.5.6.2 which failed to install.

**Comment by valderman** [comment]
What GHC version are you using, and does the problem occur with `containers-0.5.5.x` as well? I've seen this for GHC 7.6 with recent versions of `containers`. Not sure about the cause, though it should be fairly straightforward to track down with a little profiling. I hope.

**Comment by mbrodersen** [comment]
I am using GHC 7.6.3 so yes it sounds like the problem you are mentioning.

And yes it installs OK with containers-0.5.5.1

**Comment by fosskers** [comment]
I'm on `7.8.3` with containers `0.5.5.1` and seeing a similar failure, but I suppose `haste-boot` is pulling down its own `0.6.x` to build.

**Comment by mbrodersen** [comment]
Fixed on GHC 7.6.3. Closing.
