### ISSUE TITLE
haste-boot on Linux fails (this time it is bytestring-0.10.4.1)

### ISSUE THREAD

**Issue by mbrodersen** [valderman/haste-compiler#283]
(ghc 7.6.3, Ubuntu 14.10)

I tried:

$ cabal install bytestring-0.10.2.0
$ haste-boot --force --local

to fix it but haste-boot still tries to build bytestring-0.10.4.1:

Building bytestring-0.10.4.1...
Preprocessing library bytestring-0.10.4.1...

Data/ByteString/Internal.hs:212:10:
    No instance for (Control.DeepSeq.GNFData
                       (GHC.Generics.Rep ByteString))
      arising from a use of `Control.DeepSeq.$gdmrnf'
    Possible fix:
      add an instance declaration for
      (Control.DeepSeq.GNFData (GHC.Generics.Rep ByteString))
    In the expression: (Control.DeepSeq.$gdmrnf)
    In an equation for `rnf': rnf = (Control.DeepSeq.$gdmrnf)
    In the instance declaration for `NFData ByteString'
Failed to install bytestring-0.10.4.1

**Comment by mietek** [comment]
Also failing to boot on Ubuntu 14.04 and CentOS 7, using GHC 7.8.4:

```
...
Failed to install bytestring-0.10.4.1
Build log ( /root/.cabal/logs/bytestring-0.10.4.1.log ):
Configuring bytestring-0.10.4.1...
Building bytestring-0.10.4.1...
Preprocessing library bytestring-0.10.4.1...

Data/ByteString/Builder/Prim/Internal/UncheckedShifts.hs:105:8: Warning:
 In the use of ‘bitSize’
 (imported from Foreign, but defined in Data.Bits):
 Deprecated: "Use 'bitSizeMaybe' or 'finiteBitSize' instead"

Data/ByteString/Internal.hs:212:10:
 No instance for (Control.DeepSeq.GNFData
                    (GHC.Generics.Rep ByteString))
   arising from a use of ‘Control.DeepSeq.$gdmrnf’
 In the expression: Control.DeepSeq.$gdmrnf
 In an equation for ‘rnf’: rnf = Control.DeepSeq.$gdmrnf
 In the instance declaration for ‘NFData ByteString’
Building data-default-instances-dlist-0.0.1...
Installed data-default-instances-dlist-0.0.1
Installed transformers-0.4.2.0
Configuring monads-tf-0.1.0.2...
Building monads-tf-0.1.0.2...
Installed monads-tf-0.1.0.2
Installed containers-0.5.6.2
Configuring data-default-instances-containers-0.0.1...
Building data-default-instances-containers-0.0.1...
Installed data-default-instances-containers-0.0.1
Configuring data-default-0.5.3...
Building data-default-0.5.3...
Installed data-default-0.5.3
cabal: Error: some packages failed to install:
bytestring-0.10.4.1 failed during the building phase. The exception was:
ExitFailure 1
haste-lib-0.5 depends on bytestring-0.10.4.1 which failed to install.
Command '/app/bin/haste-inst' failed with error  code 1
```

**Comment by mietek** [comment]
This is caused by the `bytestring-0.10.4.1` package description on Hackage currently being broken, due to https://github.com/haskell/hackage-server/issues/305.

**Comment by crodjer** [comment]
Started happening for me as well. Same log.

**Comment by valderman** [comment]
Discussion on https://github.com/haskell/hackage-server/issues/305 indicates that this should be fixed. Confirmed?

**Comment by mbrodersen** [comment]
Yep confirm fixed. Closing.
