### ISSUE TITLE
haste-compiler-0.4.4.3 doesn't compile with GHC 7.8.4

### ISSUE THREAD

**Issue by peti** [valderman/haste-compiler#294]
Citing from http://hydra.cryp.to/build/599496/log/raw:

    src/Data/JSTarget/PP.hs:87:22:
        No instance for (IsString Builder) arising from the literal ‘"  "’
        In the ‘indentStr’ field of a record
        In the expression:
          def
            {nameComments = True, useIndentation = True, indentStr = "  ",
             useNewlines = True, useSpaces = True}
        In an equation for ‘debugPPOpts’:
            debugPPOpts
              = def
                  {nameComments = True, useIndentation = True, indentStr = "  ",
                   useNewlines = True, useSpaces = True}

**Comment by valderman** [comment]
This should be fixed with 0.4.4.4. I gave up trying to juggle those different library versions and just added a dependency on `bytestring >= 0.10.4`. Can you confirm that it is indeed fixed?

**Comment by peti** [comment]
Yes, the new version compiles fine: http://hydra.cryp.to/job/nixpkgs/haskell-updates/haskellngPackages.haste-compiler.x86_64-linux.
