### ISSUE TITLE
NaN handled differently between GHC and Haste

### ISSUE THREAD

**Issue by profil** [valderman/haste-compiler#295]
```haskell
module Main where
main = putStrLn $ show (round (0/0) :: Int)
```

The output produced by GHC is `0` and the output produced by Node.js after compiling with Haste is `NaN`. Even though this is about NaN, shouldn't the result be the same in both cases?

This difference (bug?) was found when using the quickcheck generated testing data on my fork https://github.com/profil/haste-compiler/tree/tests

**Comment by TazeTSchnitzel** [comment]
NaN isn't a valid `Int` value. This is clearly a bug.

**Comment by valderman** [comment]
Fixed on master.
