### ISSUE TITLE
Ubuntu 14.04.02 LTS - haste-boot cryptic error

### ISSUE THREAD

**Issue by psue99** [valderman/haste-compiler#299]
Installed latest Haskell Platform
(haskell-platform-2014.2.0.0-unknown-linux-x86_64.tar.gz )

cabal update
Compile and install zlib-1.2.8
cabal install cabal-install
sudo apt-get install bzip2 libbz2-dev
cabal install haste-compiler

haste-boot --local
include: getDirectoryContents: does not exist (No such file or directory)

What now?

**Comment by valderman** [comment]
You should only use `--local` when installing the latest dev version, and it must be run in the root of the haste-compiler source tree. Just running `haste-boot` (or `haste-boot --force` if you for some reason want to reboot an existing install) should do the trick when installing from Hackage.
