### ISSUE TITLE
Implementing touch events

### ISSUE THREAD

**Issue by agocorona** [valderman/haste-compiler#301]
I'm lost
I´m trying to handle touch events, for this purpose I have to call addEventListener with my own FFI JS code, but I can not even to invoke haskell code as a result of normal click events with my setup.

in the code below, the message "listener" appear, but not the "click" message.

`listen` is a copy of setCallback from Haste. jsSetCB is also a copy of the haste base library reduced for the click event.

But if I use the original jsSetCB defined in the Haste js base, it works, but not for touch events.

I'm lost. Help please....

```Haskell
import Haste.Perch
import Prelude hiding (div)
import Haste
import Haste.Foreign
import Unsafe.Coerce

main= do
 e <- getBody
 e' <- build (div $ ("click me" :: String)) e
 listen e' "click" $ \_ (_,_) ->  alert "click"
 



listen ::  Elem -> String -> (Int -> (Int,Int) -> IO()) -> IO Bool
listen e event f= jsSetCB e (toJSString event)  (mkCallback $! f)

jsSetCB :: Elem -> JSString -> JSFun a -> IO Bool
jsSetCB= 
  ffi $ toJSString "(function (elem, evt, cb) {\n\
    \var fun = function(x) {\n\
    \        var mpos = jsGetMouseCoords(x);\n\
    \        var mx = [0,mpos[0]];\n\
    \        var my = [0,mpos[1]];\n\
    \        (A(cb,[[0,x.button],[0,mx,my],0]));\n\
                \alert('listener');\n\
    \   }\n\
    \function setCB(elem, evt, cb) {\n\
    \if(elem.addEventListener) {\n\
    \    elem.addEventListener(evt, cb, false);\n\
    \    return true;\n\
    \} else if(elem.attachEvent) {\n\
    \    elem.attachEvent('on'+evt, cb);\n\
    \    return true;\n\
    \}\n\
    \return false;}\n\
    \return setCB(elem, evt, fun);\n\
  \}\n)"


instance Unpack  (JSFun a) where
  unpack = unsafeCoerce

instance Pack  (JSFun a) where
  pack = unsafeCoerce

-- it works with this, but not with touch event (touchstart etc neither in chrome in simulation mode nether in android)
-- foreign import ccall jsSetCB :: Elem -> JSString -> JSFun a -> IO Bool

**Comment by valderman** [comment]
Are you working against 0.4.x or against 0.5? Event handling is getting a major facelift with 0.5, so it's quite possible that you won't need to write more than five lines of Haskell to implement those events.

**Comment by agocorona** [comment]
I use the last version on hackage. 0.4 x

but looking at the 5,0 versions (which is quite different in event
treatment so i suppose that is non compatible). I found  this:

{-# NOINLINE setEvt #-}
setEvt :: Elem -> String -> (JSAny -> IO ()) -> IO Unpacked
setEvt = ffi "(function(e,name,f){e.addEventListener(name,f,false);\
             \return [f];})"

that used instead of listen/setCallback in my code run click an touchstart
events without modifying anything else in the example.

So i suppose that this is enough for adding touch events to hplayground.

2015-03-23 22:25 GMT+01:00 Anton Ekblad <notifications@github.com>:

> Are you working against 0.4.x or against 0.5? Event handling is getting a
> major facelift with 0.5, so it's quite possible that you won't need to
> write more than five lines of Haskell to implement those events.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/valderman/haste-compiler/issues/301#issuecomment-85204645>
> .
>



-- 
Alberto.
