### ISSUE TITLE
FFI example doesn't work in browsers which aren't chrome.

### ISSUE THREAD

**Issue by sleepypikachu** [valderman/haste-compiler#303]
I've tried Safari on OSX, Firefox on Windows and Linux and none of them work, no errors print to the console - the function just isn't called.

**Comment by jtojnar** [comment]
What version do you use? Works just fine for me with 0.5, Firefox @ Linux.

**Comment by sleepypikachu** [comment]
Ah shoot, didn't realise I was so far behind. I'm on 0.4.4.1

**Comment by jtojnar** [comment]
0.5 is dev version. Do you use 0.4 examples? https://github.com/valderman/haste-compiler/tree/0.4.4/examples/ffi

**Comment by sleepypikachu** [comment]
Yeah I used the 0.4 example - no difference between my git clone and this https://raw.githubusercontent.com/valderman/haste-compiler/0.4.4/examples/ffi/ffi.hs

**Comment by jtojnar** [comment]
It works for me with 0.4.4.4 from hackage too.

**Comment by sleepypikachu** [comment]
I'll give that a go later then and report back. Thanks for your help so far.

**Comment by sleepypikachu** [comment]
@jtojnar I've tried to update to 0.4.4.4 but no luck:
 % cabal install haste-compiler-0.4.4.4                            
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: haste-compiler-0.4.4.4 (user goal)
trying: either-4.3.2/installed-b19... (dependency of haste-compiler-0.4.4.4)
next goal: semigroups (dependency of either-4.3.2/installed-b19...)
rejecting: semigroups-0.16/installed-084... (conflict: semigroups =>
bytestring==0.10.0.2/installed-4f9..., haste-compiler => bytestring>=0.10.4)
rejecting: semigroups-0.16.2.2, 0.16.2.1, 0.16.2, 0.16.1, 0.16.0.1, 0.16,
0.15.4, 0.15.3, 0.15.2, 0.15.1, 0.15, 0.14, 0.13.0.1, 0.13, 0.12.2, 0.12.1,
0.12.0.1, 0.12, 0.11, 0.10, 0.9.2, 0.9.1, 0.9, 0.8.5, 0.8.4.1, 0.8.4, 0.8.3.2,
0.8.3.1, 0.8.3, 0.8.2, 0.8.0.1, 0.8, 0.7.1.2, 0.7.1.1, 0.7.1, 0.7.0, 0.6.1,
0.6, 0.5.0.2, 0.5.0.1, 0.5.0, 0.4.0, 0.3.4.2, 0.3.4.1, 0.3.4, 0.3.3, 0.3.2,
0.3.1, 0.3.0, 0.2.0, 0.1.0 (conflict: either =>
semigroups==0.16/installed-084...)
Dependency tree exhaustively searched.

I'm not really sure what this error message means - any clues?

Cheers,
Elliot

**Comment by jtojnar** [comment]
You fell into cabal hell. The easiest way out would probably be cleaning ~/.cabal, ~/.ghc and ~/.haste.

**Comment by sleepypikachu** [comment]
I'll give that a go - I can always roll back my dev vm.

**Comment by sleepypikachu** [comment]
I nuked cabal, ghc and haste as you proposed and got as far as 0.4.4.3, this didn't fix the problem I was experiencing so I've decided to live with it due to time constraints on development. Thanks for your help.
