### ISSUE TITLE
GHC 7.10 support

### ISSUE THREAD

**Issue by valderman** [valderman/haste-compiler#304]
Not much to say here. GHC 7.10 is out, it needs to be supported.

**Comment by jplatte** [comment]
+1, I would appreciate this!

**Comment by crodjer** [comment]
I tried simply removing the GHC version restrictions, but that results in a install failure. Have attached the logs.

Is there any ongoing effort on this? I use a `7.10` based system, so have the motivation to work on it, but not confident that I could get it done. I'll post updates of my experimentation.

https://gist.github.com/06ebaa1e3af2cbd27ab9

**Comment by crodjer** [comment]
I have haste successfully compiling at [my fork](https://github.com/crodjer/haste-compiler/tree/support-7.10) with help from @akru.

Although, `haste-boot` is still not working. I am using a cabal sandbox, but given `haste-boot` did work fine when I was on 7.8, I assume that shouldn't be a problem here.  The failure seem to be happening with `haste-cabal` while [configuring](https://github.com/crodjer/haste-compiler/blob/support-7.10/src/haste-boot.hs#L234) library packages.

**Comment by valderman** [comment]
There is work ongoing on this, but I haven't wanted to push the branch yet since it's rather messy at the moment. The work is currently stalled on `haste-cabal`: the current stupid wrapper version should be replaced with a patched proper `cabal-install` binary until we can get those patches into upstream. Doing this would allow us to tailor cabal's build process to Haste rather than having to fake a bunch of steps, such as building useless `.a` files and so on.

Why is this necessary for 7.10? Since we want the 7.10 edition to bring the proper `base` libraries up to date (as opposed to the 7.8 version which uses hacked-up 7.6 libraries), to avoid having to dismember those libraries too badly we're going to replace the `ghc-prim` interface to always get 32 bit primops. This is not currently the case, which is "fixed" using CPP hackery and still causes untold problems; the `cat_evals` problem reported multiple times is very likely related to this. Custom `ghc-prim` is already implemented in `ghc-simple`, but the resulting code (obviously) can't be linked against the host system's 64 bit libraries. This wouldn't be a problem if it weren't for the fact that vanilla cabal really wants those linked binaries. This could probably be hacked around by a fake `ar` binary or something, but since adding Haste support to cabal proper doesn't look very hard at all, we should just bite the bullet and do it; most problems people have with Haste right now are due to "good enough for now" hacks, and this is a good opportunity to get rid of the worst one permanently.

After that's fixed, I'm expecting the rest of the porting work to be pretty much pain free.

**Comment by crodjer** [comment]
@valderman Thanks for the detailed clarifications!

**Comment by ajnsit** [comment]
+1 Can't use haste until 7.10 support.

**Comment by crodjer** [comment]
@ajnsit I feel with the architectural improvements @valderman has pointed out, it should be worth the wait. Meanwhile, a 7.8 setup under something like Docker may work. You do end up losing integration with the host system's editor (at least partially) with this though.

**Comment by valderman** [comment]
GHC 7.10 support just pushed to master. Still some bugs left to iron out, but the basic support is there.

**Comment by ajnsit** [comment]
Great! Can't wait to try it out.
