### ISSUE TITLE
Failed to haste-boot (probably, due to integer-gmp; but what is the solution?)

### ISSUE THREAD

**Issue by achirkin** [valderman/haste-compiler#307]
I tried to install haste both 0.4.4.4 from hackage and 0.5 from git;
last attempt:
> sudo haste-boot --force --local

Gives the following error:

> \<no location info\>:
>    hastec: panic! (the 'impossible' happened)
>  (GHC version 7.8.4 for x86_64-unknown-linux):
>	cat_evals
>    integer-gmp:GHC.Integer.Type.J#{(w) d 610}
>    [ipv{v i5bD} [lid]]
>    [,]

I have:
>ghc-prim-0.3.1.0
>base-4.7.0.2
>integer-gmp-0.5.1.0

What is interesting is that haste-boot says that it installs ghc-prim-0.3.0.0. I don't know if it is somehow related to the issue.

So, what can I do about this?

Here is full log:
Reading package info from "libraries/rts.pkg" ... done.
Resolving dependencies...
Configuring ghc-prim-0.3.0.0...
Building ghc-prim-0.3.0.0...
Preprocessing library ghc-prim-0.3.0.0...
hastec: setNumCapabilities: not supported in the non-threaded RTS
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
WARNING: Unsupported PrimOp: indexCharOffAddr#
In-place registering ghc-prim-0.3.0.0...
Installing dist/build/GHC/Tuple.hi...
Installing dist/build/GHC/Types.hi...
Installing dist/build/GHC/Debug.hi...
Installing dist/build/GHC/Classes.hi...
Installing dist/build/GHC/Magic.hi...
Installing dist/build/GHC/CString.hi...
Installing dist/build/GHC/IntWord64.hi...
Reading package info from "packageconfig" ... done.
Reading package info from stdin ... done.
Cabal-1.22.2.0: Warning: library-dirs: /home/achirkin/.haste/haste-0.5.0_ghc-7.8.4/libraries/lib/Cabal doesn't exist or isn't a directory
Cabal-1.22.2.0: dependency "array-0.5.0.0-470385a50d2b78598af85cfe9d988e1b" doesn't exist (ignoring)
Cabal-1.22.2.0: dependency "base-4.7.0.2-bfd89587617e381ae01b8dd7b6c7f1c1" doesn't exist (ignoring)
Cabal-1.22.2.0: dependency "binary-0.7.1.0-f867dbbb69966feb9f5c4ef7695a70a5" doesn't exist (ignoring)
Cabal-1.22.2.0: dependency "bytestring-0.10.4.0-d6f1d17d717e8652498cab8269a0acd5" doesn't exist (ignoring)
Cabal-1.22.2.0: dependency "containers-0.5.5.1-d4bd887fb97aa3a46cbadc13709b7653" doesn't exist (ignoring)
Cabal-1.22.2.0: dependency "deepseq-1.3.0.2-63a1ab91b7017a28bb5d04cb1b5d2d02" doesn't exist (ignoring)
Cabal-1.22.2.0: dependency "directory-1.2.1.0-07cd1f59e3c6cac5e3e180019c59a115" doesn't exist (ignoring)
Cabal-1.22.2.0: dependency "filepath-1.3.0.2-25a474a9272ae6260626ce0d70ad1cab" doesn't exist (ignoring)
Cabal-1.22.2.0: dependency "pretty-1.1.1.1-0984f47ffe93ef3983c80b96280f1c3a" doesn't exist (ignoring)
Cabal-1.22.2.0: dependency "process-1.2.0.0-06c3215a79834ce4886ae686a0f81122" doesn't exist (ignoring)
Cabal-1.22.2.0: dependency "time-1.4.2-9b3076800c33f8382c38628f35717951" doesn't exist (ignoring)
Cabal-1.22.2.0: dependency "unix-2.7.0.1-f8658ba9ec1c4fba8a371a8e0f42ec6c" doesn't exist (ignoring)
Cabal-1.22.2.0: import-dirs: /home/achirkin/.haste/haste-0.5.0_ghc-7.8.4/libraries/lib/Cabal doesn't exist or isn't a directory (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Compat/CreatePipe.hi","Distribution/Compat/CreatePipe.p_hi","Distribution/Compat/CreatePipe.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Compat/Environment.hi","Distribution/Compat/Environment.p_hi","Distribution/Compat/Environment.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Compat/Exception.hi","Distribution/Compat/Exception.p_hi","Distribution/Compat/Exception.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Compat/ReadP.hi","Distribution/Compat/ReadP.p_hi","Distribution/Compat/ReadP.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Compiler.hi","Distribution/Compiler.p_hi","Distribution/Compiler.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/InstalledPackageInfo.hi","Distribution/InstalledPackageInfo.p_hi","Distribution/InstalledPackageInfo.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/License.hi","Distribution/License.p_hi","Distribution/License.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Make.hi","Distribution/Make.p_hi","Distribution/Make.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/ModuleName.hi","Distribution/ModuleName.p_hi","Distribution/ModuleName.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Package.hi","Distribution/Package.p_hi","Distribution/Package.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/PackageDescription.hi","Distribution/PackageDescription.p_hi","Distribution/PackageDescription.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/PackageDescription/Check.hi","Distribution/PackageDescription/Check.p_hi","Distribution/PackageDescription/Check.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/PackageDescription/Configuration.hi","Distribution/PackageDescription/Configuration.p_hi","Distribution/PackageDescription/Configuration.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/PackageDescription/Parse.hi","Distribution/PackageDescription/Parse.p_hi","Distribution/PackageDescription/Parse.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/PackageDescription/PrettyPrint.hi","Distribution/PackageDescription/PrettyPrint.p_hi","Distribution/PackageDescription/PrettyPrint.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/PackageDescription/Utils.hi","Distribution/PackageDescription/Utils.p_hi","Distribution/PackageDescription/Utils.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/ParseUtils.hi","Distribution/ParseUtils.p_hi","Distribution/ParseUtils.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/ReadE.hi","Distribution/ReadE.p_hi","Distribution/ReadE.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple.hi","Distribution/Simple.p_hi","Distribution/Simple.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Bench.hi","Distribution/Simple/Bench.p_hi","Distribution/Simple/Bench.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Build.hi","Distribution/Simple/Build.p_hi","Distribution/Simple/Build.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Build/Macros.hi","Distribution/Simple/Build/Macros.p_hi","Distribution/Simple/Build/Macros.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Build/PathsModule.hi","Distribution/Simple/Build/PathsModule.p_hi","Distribution/Simple/Build/PathsModule.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/BuildPaths.hi","Distribution/Simple/BuildPaths.p_hi","Distribution/Simple/BuildPaths.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/BuildTarget.hi","Distribution/Simple/BuildTarget.p_hi","Distribution/Simple/BuildTarget.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/CCompiler.hi","Distribution/Simple/CCompiler.p_hi","Distribution/Simple/CCompiler.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Command.hi","Distribution/Simple/Command.p_hi","Distribution/Simple/Command.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Compiler.hi","Distribution/Simple/Compiler.p_hi","Distribution/Simple/Compiler.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Configure.hi","Distribution/Simple/Configure.p_hi","Distribution/Simple/Configure.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/GHC.hi","Distribution/Simple/GHC.p_hi","Distribution/Simple/GHC.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/GHCJS.hi","Distribution/Simple/GHCJS.p_hi","Distribution/Simple/GHCJS.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Haddock.hi","Distribution/Simple/Haddock.p_hi","Distribution/Simple/Haddock.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/HaskellSuite.hi","Distribution/Simple/HaskellSuite.p_hi","Distribution/Simple/HaskellSuite.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Hpc.hi","Distribution/Simple/Hpc.p_hi","Distribution/Simple/Hpc.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Install.hi","Distribution/Simple/Install.p_hi","Distribution/Simple/Install.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/InstallDirs.hi","Distribution/Simple/InstallDirs.p_hi","Distribution/Simple/InstallDirs.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/JHC.hi","Distribution/Simple/JHC.p_hi","Distribution/Simple/JHC.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/LHC.hi","Distribution/Simple/LHC.p_hi","Distribution/Simple/LHC.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/LocalBuildInfo.hi","Distribution/Simple/LocalBuildInfo.p_hi","Distribution/Simple/LocalBuildInfo.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/PackageIndex.hi","Distribution/Simple/PackageIndex.p_hi","Distribution/Simple/PackageIndex.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/PreProcess.hi","Distribution/Simple/PreProcess.p_hi","Distribution/Simple/PreProcess.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/PreProcess/Unlit.hi","Distribution/Simple/PreProcess/Unlit.p_hi","Distribution/Simple/PreProcess/Unlit.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Program.hi","Distribution/Simple/Program.p_hi","Distribution/Simple/Program.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Program/Ar.hi","Distribution/Simple/Program/Ar.p_hi","Distribution/Simple/Program/Ar.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Program/Builtin.hi","Distribution/Simple/Program/Builtin.p_hi","Distribution/Simple/Program/Builtin.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Program/Db.hi","Distribution/Simple/Program/Db.p_hi","Distribution/Simple/Program/Db.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Program/Find.hi","Distribution/Simple/Program/Find.p_hi","Distribution/Simple/Program/Find.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Program/GHC.hi","Distribution/Simple/Program/GHC.p_hi","Distribution/Simple/Program/GHC.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Program/HcPkg.hi","Distribution/Simple/Program/HcPkg.p_hi","Distribution/Simple/Program/HcPkg.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Program/Hpc.hi","Distribution/Simple/Program/Hpc.p_hi","Distribution/Simple/Program/Hpc.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Program/Ld.hi","Distribution/Simple/Program/Ld.p_hi","Distribution/Simple/Program/Ld.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Program/Run.hi","Distribution/Simple/Program/Run.p_hi","Distribution/Simple/Program/Run.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Program/Script.hi","Distribution/Simple/Program/Script.p_hi","Distribution/Simple/Program/Script.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Program/Strip.hi","Distribution/Simple/Program/Strip.p_hi","Distribution/Simple/Program/Strip.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Program/Types.hi","Distribution/Simple/Program/Types.p_hi","Distribution/Simple/Program/Types.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Register.hi","Distribution/Simple/Register.p_hi","Distribution/Simple/Register.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Setup.hi","Distribution/Simple/Setup.p_hi","Distribution/Simple/Setup.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/SrcDist.hi","Distribution/Simple/SrcDist.p_hi","Distribution/Simple/SrcDist.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Test.hi","Distribution/Simple/Test.p_hi","Distribution/Simple/Test.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Test/ExeV10.hi","Distribution/Simple/Test/ExeV10.p_hi","Distribution/Simple/Test/ExeV10.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Test/LibV09.hi","Distribution/Simple/Test/LibV09.p_hi","Distribution/Simple/Test/LibV09.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Test/Log.hi","Distribution/Simple/Test/Log.p_hi","Distribution/Simple/Test/Log.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/UHC.hi","Distribution/Simple/UHC.p_hi","Distribution/Simple/UHC.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/UserHooks.hi","Distribution/Simple/UserHooks.p_hi","Distribution/Simple/UserHooks.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/Utils.hi","Distribution/Simple/Utils.p_hi","Distribution/Simple/Utils.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/System.hi","Distribution/System.p_hi","Distribution/System.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/TestSuite.hi","Distribution/TestSuite.p_hi","Distribution/TestSuite.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Text.hi","Distribution/Text.p_hi","Distribution/Text.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Utils/NubList.hi","Distribution/Utils/NubList.p_hi","Distribution/Utils/NubList.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Verbosity.hi","Distribution/Verbosity.p_hi","Distribution/Verbosity.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Version.hi","Distribution/Version.p_hi","Distribution/Version.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Language/Haskell/Extension.hi","Language/Haskell/Extension.p_hi","Language/Haskell/Extension.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Compat/Binary.hi","Distribution/Compat/Binary.p_hi","Distribution/Compat/Binary.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Compat/CopyFile.hi","Distribution/Compat/CopyFile.p_hi","Distribution/Compat/CopyFile.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Compat/TempFile.hi","Distribution/Compat/TempFile.p_hi","Distribution/Compat/TempFile.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/GetOpt.hi","Distribution/GetOpt.p_hi","Distribution/GetOpt.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/GHC/Internal.hi","Distribution/Simple/GHC/Internal.p_hi","Distribution/Simple/GHC/Internal.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/GHC/IPI641.hi","Distribution/Simple/GHC/IPI641.p_hi","Distribution/Simple/GHC/IPI641.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/GHC/IPI642.hi","Distribution/Simple/GHC/IPI642.p_hi","Distribution/Simple/GHC/IPI642.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Distribution/Simple/GHC/ImplInfo.hi","Distribution/Simple/GHC/ImplInfo.p_hi","Distribution/Simple/GHC/ImplInfo.dyn_hi"] (ignoring)
Cabal-1.22.2.0: cannot find any of ["Paths_Cabal.hi","Paths_Cabal.p_hi","Paths_Cabal.dyn_hi"] (ignoring)
Resolving dependencies...
Configuring integer-gmp-0.5.0.0...
Building integer-gmp-0.5.0.0...
Installed integer-gmp-0.5.0.0
Resolving dependencies...
Configuring base-4.6.0.1...
Warning: Instead of 'ghc-options: -XCPP' use 'extensions: CPP'
Building base-4.6.0.1...
Preprocessing library base-4.6.0.1...

Foreign/C/Error.hs:3:16: Warning:
    -#include and INCLUDE pragmas are deprecated: They no longer have any effect

GHC/Unicode.hs:3:12: Warning:
    -#include and INCLUDE pragmas are deprecated: They no longer have any effect
hastec: setNumCapabilities: not supported in the non-threaded RTS

GHC/Float.lhs:980:1: Warning:
    Forall'd type variable ‘a’ is not bound in RULE lhs
      fromIntegral @ a @ b $dIntegral_a2la $dNum_a2lb

GHC/Float.lhs:981:1: Warning:
    Forall'd type variable ‘a’ is not bound in RULE lhs
      fromIntegral @ a @ b $dIntegral_a2kX $dNum_a2kY

GHC/Float.lhs:983:1: Warning:
    Forall'd type variable ‘a’ is not bound in RULE lhs
      realToFrac @ a @ b $dReal_a2kD $dFractional_a2kE

GHC/Float.lhs:984:1: Warning:
    Forall'd type variable ‘a’ is not bound in RULE lhs
      realToFrac @ a @ b $dReal_a2kr $dFractional_a2ks

GHC/Float.lhs:986:1: Warning:
    Forall'd type variable ‘a’ is not bound in RULE lhs
      realToFrac @ a @ b $dReal_a2k7 $dFractional_a2k8

GHC/Float.lhs:987:1: Warning:
    Forall'd type variable ‘a’ is not bound in RULE lhs
      realToFrac @ a @ b $dReal_a2jF $dFractional_a2jG

<no location info>:
    hastec: panic! (the 'impossible' happened)
  (GHC version 7.8.4 for x86_64-unknown-linux):
	cat_evals
    integer-gmp:GHC.Integer.Type.J#{(w) d 610}
    [ipv{v i5bD} [lid]]
    [,]

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

**Comment by valderman** [comment]
What happens if you omit the `sudo`? Since Haste package directories and settings are per user (unless build with the `portable` flag, like the binaries on http://haste-lang.org/downloads), booting as root may produce "interesting" results.

**Comment by achirkin** [comment]
Unfortunately, exactly the same result.
By the way, I wonder why haste-compiler builds another set of versions instead of building the same versions as cabal has (integer-gmp-0.5.0.0 instead of 0.5.1.0, ghc-prim-0.3.0.0 instead of ghc-prim-0.3.1.0, base-base-4.6.0.1 instead of 4.7.0.2, which are installed in my system)?

**Comment by valderman** [comment]
Haste builds its own versions as the browser is quite a different environment from the C/operating system world that Haskell programs normally inhabit. For one, the browser is for all intents and purposes a 32 bit architecture while your build system is probably a 64 bit one. GHC not being very amenable to being used as a cross compiler (and even less so when first getting `base` and the other libraries to build with Haste back in 2012) gives rise to some "creative" solutions, which maybe ought to be cleaned up some time.

Do you have a cabal sandbox lying around, interfering with things? `haste-cabal` (and, by extension, `haste-boot`) doesn't currently work well with those.

**Comment by achirkin** [comment]
No, but I have installed GHC and packages globally, under not usual path (/usr/local/haskell/ghc-7.8.4). Today I reinstalled everything, put haste-compiler as user package and booted seemingly normally. Maybe the problem was haste-compiler installed into global path, maybe I just garbaged my installation, I do not know.

**Comment by valderman** [comment]
Is this problem still present in master? `haste-cabal` got completely redone, so chances are good this bug got zapped in the process.

**Comment by valderman** [comment]
...and now the cat_evals problem is definitely fixed on master as well.
