### ISSUE TITLE
Give a way to alert if we can't connect to the server

### ISSUE THREAD

**Issue by rlpowell** [valderman/haste-compiler#309]
As far as I can tell from brief digging (in particular, looking at Haste.WebSockets) there is no way for the client to know that the websocket connection failed, except to write our own javascript.  Can we have something in Haskell for this?  Thanks!

**Comment by valderman** [comment]
The third argument to `withWebSocket` is a computation that gets invoked when an error occurs, usually the connection failing or getting terminated. Do you need any additional info about why the connection was terminated for your use case?

**Comment by rlpowell** [comment]
I was playing with the example apps, and the only way I was able to figure out why it wasn't working (host name issue with the WS connection) was by launching the javascript console.  Even with the server completely inaccessible, I never saw an error of any kind.

Now that I know what to look for, I see that runClient *does* have an error handler, but in the case of never having connected, it doesn't seem to fire.

**Comment by valderman** [comment]
That's definitely a problem. Will look into it.
