### ISSUE TITLE
Feature request: requestAnimationFrame

### ISSUE THREAD

**Issue by TazeTSchnitzel** [valderman/haste-compiler#312]
Sorry for all the issues! I'm quite enjoying using Haste (I got a raycaster running in it!), so I guess it's just a product of using it a bit. It's awesome being able to run Haskell code in the browser.

I was wondering if you'd consider adding a shortcut for `requestAnimationFrame` to the `Haste` module. It's a browser API similar to `setTimeout`, but rather than specifying a timeout, the browser will run the callback when it's next ready to update the screen. This means you can get nice and smooth animation, and avoid wasting CPU time (and thus battery life) when you're in another tab.

It's not an absolute requirement, of course, as you can just use `Haste.Foreign`. But it's quite a common use case, so I think it'd make sense to have it.

If I'm bothered enough there's a chance I might add this myself, but don't count on it.

(Along the same lines: maybe there's a case for `setInterval` as well? I hope I'm not being too demanding, I just want to be helpful.)

**Comment by jtojnar** [comment]
There already is `setInterval` in 0.5 (https://github.com/valderman/haste-compiler/blob/4341f78f6750c74a4faf1fa4b3749e0a87f095d6/libraries/haste-lib/src/Haste/Timer.hs), adding `requestAnimationFrame` shouldn’t be that hard.

**Comment by TazeTSchnitzel** [comment]
Ah, great :)

**Comment by TazeTSchnitzel** [comment]
For this to be useful you also need to be able to get the current time so you can find a delta. I don't if Haste has functions for this currently. Does it? Is there a list somewhere of what packages Haste has?

I just did this:

```Haskell
-- Current time in seconds (for delta purposes)
-- getCPUTime returns picoseconds (10^-12)
now :: IO Double
now = ffi $ toJSStr "(function () { return (new Date()).getTime() / 1000; })"
```

**Comment by TazeTSchnitzel** [comment]
Example usage:

    let rots_per_sec    = 0.5
        tau             = 2 * pi

    time <- now
    requestAnimationFrame $ do
        newTime <- now
        let delta = newTime - time
            increment = delta * rots_per_sec * tau
        renderGame canvas pos (rot dir $ -increment) (rot plane $ -increment)

**Comment by jtojnar** [comment]
Haddock offers a [list](http://haste-lang.org/docs/haddock/0.4.4/doc-index-All.html). For 0.5 you would need to run `cabal haddock` in the haste-compiler directory.

Maybe @valderman could setup a CI to automatically build the documentation for master.

**Comment by TazeTSchnitzel** [comment]
I don't mean just what the module `Haste` has, hackage has a contents listing for that. Rather, what other Haskell modules does it have? Is it just that and base?

**Comment by valderman** [comment]
You can use `getCurrentTime` from the `time` package to get the current wall clock time. Fixes incoming for performance counters and requesting animation frames.

As for packaged libs, Haste currently comes with the tightly compiler-dependent stuff (ghc-prim, integer-gmp, base and haste-lib) plus arrays, containers, deepseq and transformers. The distribution should probably include a few other things as well (time, for instance) to encourage their use, however.
