### ISSUE TITLE
Can't install missingh or time or ...

### ISSUE THREAD

**Issue by rlpowell** [valderman/haste-compiler#316]
My apologies if this is a repeat, but it seems like every package I try to install ends sooner or later with something like this:

    3989f51f5942# haste-cabal --version
    cabal-install version 1.22.4.0
    using version 1.22.3.0 of the Cabal library
    3989f51f5942# which haste-cabal
    /root/.cabal/bin/haste-cabal
    3989f51f5942# haste-cabal install time
    Resolving dependencies...
    Configuring time-1.5.0.1...
    Failed to install time-1.5.0.1
    Build log ( /root/.cabal/logs/time-1.5.0.1.log ):
    cabal: Error: some packages failed to install:
    time-1.5.0.1 failed during the configure step. The exception was:
    user error ('/root/.cabal/bin/hastec' exited with an error:
    hastec: <command line>: cannot satisfy -package-id
    Cabal-1.22.3.0-3946c8d169790a47c6ea9d73b01d3fa0:
    Cabal-1.22.3.0-3946c8d169790a47c6ea9d73b01d3fa0 is unusable due to missing or
    recursive dependencies:
    array-0.5.0.0-470385a50d2b78598af85cfe9d988e1b
    base-4.7.0.2-bfd89587617e381ae01b8dd7b6c7f1c1
    binary-0.7.1.0-f867dbbb69966feb9f5c4ef7695a70a5
    bytestring-0.10.4.0-d6f1d17d717e8652498cab8269a0acd5
    containers-0.5.5.1-d4bd887fb97aa3a46cbadc13709b7653
    deepseq-1.3.0.2-63a1ab91b7017a28bb5d04cb1b5d2d02
    directory-1.2.1.0-07cd1f59e3c6cac5e3e180019c59a115
    filepath-1.3.0.2-25a474a9272ae6260626ce0d70ad1cab
    pretty-1.1.1.1-0984f47ffe93ef3983c80b96280f1c3a
    process-1.2.0.0-06c3215a79834ce4886ae686a0f81122
    time-1.4.2-9b3076800c33f8382c38628f35717951
    unix-2.7.0.1-f8658ba9ec1c4fba8a371a8e0f42ec6c
    (use -v for more information)
    )

**Comment by rlpowell** [comment]
This includes trying to fix it by installing Cabal-1.22.3.0 , which ends with:

unix-2.7.1.0 depends on time-1.5.0.1 which failed to install.

Or at least it did this time; it seems to be somewhat non-deterministic.

**Comment by rlpowell** [comment]
So I moved the complicated code to the server side (which process really needs
a tutorial), and now the *only* thing haste needs is regex-tdfa, but I can't
seem to even do that.  Here's me trying on a fresh docker:


        5b280d55a8e5# haste-cabal install regex-tdfa
        Resolving dependencies...
        In order, the following will be installed:
        binary-0.7.4.0 (via: text-1.2.1.0) (new package)
        mtl-2.2.1 (via: regex-tdfa-1.2.0 parsec-3.1.9 regex-base-0.93.2) (reinstall) (changes: base-4.6.0.1 added)
        regex-base-0.93.2 (via: regex-tdfa-1.2.0) (reinstall) (changes: array-0.4.0.1 added, base-4.6.0.1 added, bytestring-0.10.6.0 added, containers-0.4.1.0 added, mtl-2.1.3.1 -> 2
        .2.1)
        text-1.2.1.0 -integer-simple (via: parsec-3.1.9) (reinstall) (changes: array-0.4.0.1 added, base-4.6.0.1 added, binary-0.7.4.0 added, bytestring-0.10.6.0 added, deepseq-1.4.1
        .1 added, ghc-prim-0.3.0.0 added, integer-gmp-0.5.0.0 added)
        parsec-3.1.9 (via: regex-tdfa-1.2.0) (reinstall) (changes: base-4.6.0.1 added, bytestring-0.10.6.0 added, mtl-2.1.3.1 -> 2.2.1)
        regex-tdfa-1.2.0 (reinstall) (changes: array-0.4.0.1 added, base-4.6.0.1 added, bytestring-0.10.6.0 added, containers-0.4.1.0 added, ghc-prim-0.3.0.0 added, mtl-2.1.3.1 -> 2.
        2.1)
        Warning: Note that reinstalls are always dangerous. Continuing anyway...
        Downloading binary-0.7.4.0...
        Configuring mtl-2.2.1...
        Configuring binary-0.7.4.0...
        Building mtl-2.2.1...
        Building binary-0.7.4.0...
        Failed to install binary-0.7.4.0
        Build log ( /root/.cabal/logs/binary-0.7.4.0.log ):
        Configuring binary-0.7.4.0...
        Building binary-0.7.4.0...
        Preprocessing library binary-0.7.4.0...
        
        src/Data/Binary/Builder/Base.hs:192:37: Warning:
            In the use of �inlinePerformIO�
            (imported from Data.ByteString.Internal):
            Deprecated: "If you think you know what you are doing, use 'unsafePerformIO'. If you are sure you know what you are doing, use 'unsafeDupablePerformIO'. If you enjoy shar
        ing an address space with a malevolent agent of chaos, try 'accursedUnutterablePerformIO'."
        
        src/Data/Binary/Get/Internal.hs:402:21: Warning:
            In the use of �B.inlinePerformIO�
            (imported from Data.ByteString.Internal):
            Deprecated: "If you think you know what you are doing, use 'unsafePerformIO'. If you are sure you know what you are doing, use 'unsafeDupablePerformIO'. If you enjoy shar
        ing an address space with a malevolent agent of chaos, try 'accursedUnutterablePerformIO'."
        
        src/Data/Binary/Get/Internal.hs:369:1: Warning:
            Rule "<$> to <*>" may never fire because �<$>� might inline first
            Probable fix: add an INLINE[n] or NOINLINE[n] pragma on �<$>�
        
        src/Data/Binary/Get.hs:434:1: Warning:
            Rule "getWord8/readN" may never fire
              because �getWord8� might inline first
            Probable fix: add an INLINE[n] or NOINLINE[n] pragma on �getWord8�
        
        src/Data/Binary/Get.hs:435:1: Warning:
            Rule "getWord16be/readN" may never fire
              because �getWord16be� might inline first
            Probable fix: add an INLINE[n] or NOINLINE[n] pragma on �getWord16be�
        
        src/Data/Binary/Get.hs:436:1: Warning:
            Rule "getWord16le/readN" may never fire
              because �getWord16le� might inline first
            Probable fix: add an INLINE[n] or NOINLINE[n] pragma on �getWord16le�
        
        src/Data/Binary/Get.hs:437:1: Warning:
            Rule "getWord32be/readN" may never fire
              because �getWord32be� might inline first
            Probable fix: add an INLINE[n] or NOINLINE[n] pragma on �getWord32be�
        
        src/Data/Binary/Get.hs:438:1: Warning:
            Rule "getWord32le/readN" may never fire
              because �getWord32le� might inline first
            Probable fix: add an INLINE[n] or NOINLINE[n] pragma on �getWord32le�
        
        src/Data/Binary/Get.hs:439:1: Warning:
            Rule "getWord64be/readN" may never fire
              because �getWord64be� might inline first
            Probable fix: add an INLINE[n] or NOINLINE[n] pragma on �getWord64be�
        
        src/Data/Binary/Get.hs:440:1: Warning:
            Rule "getWord64le/readN" may never fire
              because �getWord64le� might inline first
            Probable fix: add an INLINE[n] or NOINLINE[n] pragma on �getWord64le�
        hastec: hastec: panic! (the 'impossible' happened)
          (GHC version 7.8.4 for x86_64-unknown-linux):
                cat_evals
        <<details unavailable>>
        
        Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
        
        Installed mtl-2.2.1
        Configuring regex-base-0.93.2...
        Building regex-base-0.93.2...
        Installed regex-base-0.93.2
        cabal: Error: some packages failed to install:
        binary-0.7.4.0 failed during the building phase. The exception was:
        ExitFailure 1
        parsec-3.1.9 depends on binary-0.7.4.0 which failed to install.
        regex-tdfa-1.2.0 depends on binary-0.7.4.0 which failed to install.
        text-1.2.1.0 depends on binary-0.7.4.0 which failed to install.
        5b280d55a8e5#
        
Help?

**Comment by rlpowell** [comment]
So it turns out that:

haste-cabal install --avoid-reinstalls regex-tdfa

goes much better.  Whoops.

However, this time it fills up all available RAM (about 2GiB) and makes the machine unusable and basically never ends (5+ hours).  -_-

**Comment by rlpowell** [comment]
Specifically, the thing that takes all my RAM is:

      /root/.cabal/bin/hastec --make -fbuilding-cabal-package -O -outputdir dist/build -odir dist/build -hidir dist/build -stubdir dist/build -i -idist/build -i. -idist/build/autogen -Idist/build/autogen -Idist/build -optP-include -optPdist/build/autogen/cabal_macros.h -package-name regex-tdfa-1.1.8 -hide-all-packages -package-db /root/.haste/haste-0.5.0_ghc-7.8.4/packages -package-db /root/.haste/haste-0.5.0_ghc-7.8.4/packages -package-db dist/package.conf.inplace -package-id array-0.4.0.1- -package-id base-4.6.0.1 -package-id bytestring-0.10.6.0- -package-id containers-0.4.1.0- -package-id ghc-prim-0.3.0.0-d5221a8c8a269b66ab9a07bdc23317dd -package-id mtl-2.2.1- -package-id parsec-3.1.8- -package-id regex-base-0.93.2- -XHaskell98 -XMultiParamTypeClasses -XFunctionalDependencies -XBangPatterns -XMagicHash -XRecursiveDo -XNoMonoPatBinds -XForeignFunctionInterface -XUnboxedTuples -XTypeOperators -XFlexibleContexts -XExistentialQuantification -XUnliftedFFITypes -XTypeSynonymInstances -XFlexibleInstances Data.IntMap.CharMap2 Data.IntMap.EnumMap2 Data.IntSet.EnumSet2 Text.Regex.TDFA Text.Regex.TDFA.ByteString Text.Regex.TDFA.ByteString.Lazy Text.Regex.TDFA.Common Text.Regex.TDFA.CorePattern Text.Regex.TDFA.IntArrTrieSet Text.Regex.TDFA.NewDFA.Engine Text.Regex.TDFA.NewDFA.Engine_FA Text.Regex.TDFA.NewDFA.Engine_NC Text.Regex.TDFA.NewDFA.Engine_NC_FA Text.Regex.TDFA.NewDFA.Tester Text.Regex.TDFA.NewDFA.Uncons Text.Regex.TDFA.NewDFA.MakeTest Text.Regex.TDFA.Pattern Text.Regex.TDFA.ReadRegex Text.Regex.TDFA.Sequence Text.Regex.TDFA.String Text.Regex.TDFA.TDFA Text.Regex.TDFA.TNFA Paths_regex_tdfa -Wall -funbox-strict-fields -fspec-constr-count=10 -O2 -fno-warn-orphans --libinstall

**Comment by rlpowell** [comment]
By running "haste-cabal install regex-base" followed by "haste-cabal install --avoid-reinstalls regex-tdfa" and killing absolutely everything I could find on my system that wasn't required to run, I managed to get regex-tdfa installed.  Woo.  Any hints on how I can control the RAM issue?

**Comment by rlpowell** [comment]
For anyone else viewing this in the future: "haste-cabal install regex-base" followed by "haste-cabal install --avoid-reinstalls regex-pcre" is *WAY* nicer on RAM.  :D

**Comment by valderman** [comment]
This issue has a whole bunch of interesting sub-issues. I have no idea why splitting the regex-tdfa thing works, that just seems weird, and the memory thing *definitely* needs some urgent investigation!

For regexes, you may want to consider using `Haste.JSString` which wraps browser builtins rather than pure Haskell solutions, for size and speed reasons. Only on the as-yet unreleased 0.5 branch, however.

**Comment by valderman** [comment]
@rlpowell I've been hacking a bit on the optimizer these last few days, resulting in a 90% reduction in run time and (at least) 50% reduction in memory use when building my completely arbitrarily chosen test case (`containers-0.5.6.3`), while also producing slightly better code. It'll probably help even more for larger examples.

There's still some relatively low hanging fruit left in the optimizer, but I decided to stop here for the moment since the vast majority of time is now spent in GHC anyway.

**Comment by valderman** [comment]
Fixed on master with GHC 7.10.
