### ISSUE TITLE
Apply function makes profiling impossible in Firefox

### ISSUE THREAD

**Issue by TazeTSchnitzel** [valderman/haste-compiler#318]
Instead of seeing a full breakdown, you just see the entire CPU time taken up by calls to A:

```JavaScript
/* Apply
   Applies the function f to the arguments args. If the application is under-
   saturated, a closure is returned, awaiting further arguments. If it is over-
   saturated, the function is fully applied, and the result (assumed to be a
   function) is then applied to the remaining arguments.
*/
function A(f, args) {
    if(f instanceof T) {
        f = E(f);
    }
    // Closure does some funny stuff with functions that occasionally
    // results in non-functions getting applied, so we have to deal with
    // it.
    if(!(f instanceof Function)) {
        f = B(f);
        if(!(f instanceof Function)) {
            return f;
        }
    }

    if(f.arity === undefined) {
        f.arity = f.length;
    }
    if(args.length === f.arity) {
        switch(f.arity) {
            case 0:  return f();
            case 1:  return f(args[0]);
            default: return f.apply(null, args);
        }
    } else if(args.length > f.arity) {
        switch(f.arity) {
            case 0:  return f();
            case 1:  return A(f(args.shift()), args);
            default: return A(f.apply(null, args.splice(0, f.arity)), args);
        }
    } else {
        var g = function() {
            return A(f, args.concat(Array.prototype.slice.call(arguments)));
        };
        g.arity = f.arity - args.length;
        return g;
    }
}
```

I'm not sure if much can really be done about this. Really, it probably just reflects a problem with Firefox, if it doesn't seem to detect `.apply()` calls. But I'm wondering if maybe it could be worked around, somehow.

**Comment by valderman** [comment]
The apply function presents problems for ongoing work on information flow tracking as well, and is slow and kind of a jerk to the GC as well! Getting rid of it has been a TODO thing for a long time, but hasn't been done yet.

Would happily merge any patch that replaces it with something less stupid.

**Comment by TazeTSchnitzel** [comment]
It looks like apply exists to curry non-curried functions. But that begs the question: why isn't everything already curried?

**Comment by TazeTSchnitzel** [comment]
In browsers that support them, ES6 splats are an option. The first branch becomes:

```JavaScript
    if(args.length === f.arity) {
        switch(f.arity) {
            case 0:  return f();
            case 1:  return f(args[0]);
            default: return f(...args);
        }
```

The second:

```JavaScript
    } else if(args.length > f.arity) {
        switch(f.arity) {
            case 0:  return f();
            ase 1:  return A(f(args.shift()), args);
            default: return A(f(...args.splice(0, f.arity)), args);
        }
```

The third:

```JavaScript
    } else {
        var g = function() {
            return A(f, args, ...Array.prototype.slice.call(arguments));
        };
        g.arity = f.arity - args.length;
        return g;
    }
```

Given how this simplifies things, it might be possible to simplify and inline this? Who knows.

Not sure yet if it improves performance or profiling.

**Comment by valderman** [comment]
In the STG we get back from GHC there are still partial applications, so they need to be handled somehow. `A()` is a catch-all solution to that problem, but not a very good one.

**Comment by valderman** [comment]
Does b46c96f help at all WRT profiling, since we don't do stupid stuff with closures anymore?

**Comment by TazeTSchnitzel** [comment]
I'd test this out, but I've had trouble setting up an environment where I can develop Haste. It doesn't seem to like booting within a cabal sandbox, for example.

**Comment by TazeTSchnitzel** [comment]
I decided to just install globally instead from git. Unfortunately, now my code won't run at all: https://github.com/valderman/haste-compiler/issues/324

**Comment by TazeTSchnitzel** [comment]
However, it seems the profiling situation wasn't quite as bad as I thought it was. I might not have been looking in the right place in the tree before.
