### ISSUE TITLE
Using haste with stack - "couldn't find Haste.Events" error

### ISSUE THREAD

**Issue by jhoxray** [valderman/haste-compiler#325]
Trying to migrate to `stack` instead of `cabal` (mostly because of default sandboxing and stable package tree). Installed haste with `stack install haste-compiler` (which installs into stack snapshots directory). When trying to compile an example - get the "couldn't find Haste.Events" error message, for obvious reasons I assume that `hastec` doesn't know where to look for installed packages. Question: is there any way to tell `hastec` where to look?
EDITED: .. or not so obvious, as Haste.Events is not in the main haste library?? Where is it?

**Comment by jtojnar** [comment]
The examples in the repository may use features from development versions of the library.
Try https://github.com/valderman/haste-compiler/tree/0.4.4/examples

See also #303

**Comment by valderman** [comment]
As per @jtojnar's comment, this would seem to be fixed as there has been no word to the contrary. Please reopen with repro instructions if this is not the case.
