### ISSUE TITLE
Data.Time getCurrentTime yields "Invalid left-hand side in assignment" error

### ISSUE THREAD

**Issue by nyson** [valderman/haste-compiler#329]
Hello!

Data.Time is a bit broken in haste 0.5.0. The code below yields a "invalid left-hand side in assignment" error, with the generated code `0 = 0;`.

```haskell
import Data.Time
main = do
  time <- getCurrentTime
  return ()
```

Tested on commit 1df911b3a175176821d30635a2d08b955015e6d5

**Comment by valderman** [comment]
Fixed in 883522bdf92aed933f0c66c911fa41904cc2bc32. Now it breaks due to an unimplemented primop instead.
