### ISSUE TITLE
newSeed in callback causes javascript error in browser

### ISSUE THREAD

**Issue by dc25** [valderman/haste-compiler#332]
This bit of code works just fine in haste 0.5.0 but produces a javascript error when compiled with haste 0.5.1.2.   Please let me know if you need more details.  This happens when running in Chrome 44 on Ubuntu 14.04 - I didn't try any other setups.

    {-# LANGUAGE OverloadedStrings #-}
    import Haste
    import Haste.Foreign
    import Haste.App 

    consoleLog_ffi :: String-> IO ()
    consoleLog_ffi = ffi "(function (msg) { console.log(msg); })"

    foo_ffi :: (IO ()) -> IO ()
    foo_ffi = ffi "(function (cb) { cb(); })"

    main = foo_ffi(loadCallback) where
        loadCallback = do
            gen <- newSeed 
            consoleLog_ffi "hello world2"

**Comment by valderman** [comment]
Is this with the GHC 7.10 version, or with 7.8?

**Comment by valderman** [comment]
Nevermind, the problem exists in both versions as it's related to some changes in the interface of the MD5 implementation between 0.5.0 and 0.5.1. Fix coming soon.

**Comment by dc25** [comment]
I'm still seeing this problem with the latest haste from the master
branch.  Did you rerun my test with your fix in place?

I'm using ghc 7.8.4 .

**Comment by valderman** [comment]
Yes, I can't reproduce the problem after the fix. Did you both install and reboot Haste from master? (`haste-boot --force --local`)

**Comment by dc25** [comment]
Yes, I did both of those things.  Here's the difference in js files that I
see :

root@a32b0f454623:/repos/gitnc/hasteBug# diff main.js
main.js.haste_with_bugfix
NG.                                            │2031a2032
+-- | Generate a new seed using Javascript's PR│> window['newByteArr'] =
newByteArr;

It looks like the newByteArr diff is part of the bug fix so I am getting at
least some of your fix.

I'm trying to think of some way that I might not have gotten the whole fix
installed but nothing comes to mind.  I re-cloned, rebuilt, and re-booted
from scratch in an environment that had no haste to begin with.  I checked
the git log and see your fix.

I'm using ubuntu/vivid - could that be relevant?

**Comment by valderman** [comment]
Your OS shouldn't have any bearing on this bug, it's a pretty straightforward mistake in one of the libraries. This seems consistent with forgetting or mistyping `--local` when running `haste-boot`: JS lib update gets installed by `cabal install`, while the old libraries are used for booting. `haste-boot` currently doesn't even complain when it gets an unrecognized option (which it really should), so it's pretty easy to make a mistake there.

Could you describe in more detail the exact steps you took to install and boot the fixed version?

**Comment by dc25** [comment]
Yeah,  I know that the operating system shouldn't have any bearing on the
bug.  I was just racking my brain trying to think of something that might
be different.

My development environment is a docker image.  I  just started rebuilding
that from scratch right now.    When that build completes, I'll try the
test again and let you know what the results are.  If the test fails, I'll
include more details about the setup.

**Comment by dc25** [comment]
The problem was (as you suggested) a mistyped "--local" .   The bug is fixed.

**Comment by valderman** [comment]
Great, thanks for the help in tracking down this problem!
