### ISSUE TITLE
Support for touch events

### ISSUE THREAD

**Issue by kranich** [valderman/haste-compiler#334]
Adding support for touch events (http://www.w3.org/TR/touch-events/) to Haste would be nice.

**Comment by kranich** [comment]
I noticed that on some mobile devices, touches are not generating corresponding mouse events, which breaks interaction.

**Comment by valderman** [comment]
1070b0ff06bf6ad8cdfe01697722f3463b06c2b3 adds support for touchstart/-move/-end/-cancel. Could you try it out and see if the API works well, or if it needs some changes?

**Comment by kranich** [comment]
Works like a charm, thanks a lot!
