### ISSUE TITLE
OS X pre-built package is broken

### ISSUE THREAD

**Issue by pnutus** [valderman/haste-compiler#342]
The OS X package linked [here](http://haste-lang.org/downloads/) is broken. I suspect the wrong file has been uploaded.

* The filename `haste-compiler-0.5.1.3_ghc-7.10.2-darwin.tar.bz2` seems to suggest that it is not the version claimed on the page (0.5.2). The other packages' filenames all say 0.5.2.
* When I run `md5 haste-compiler-0.5.1.3_ghc-7.10.2-darwin.tar.bz2` I get `82da40f69a53031f7fbf1f9be06cae08` which is not same as the one claimed on the webpage (`b63fe4ba48638e412c5d1ca1f4122870`).
* The `install.sh` script tells me to `Please run the Haste installer from the root of the unpacked
binary distribution.`, even when I'm doing just that. The script seems to be looking for a subdirectory `haste-cabal` which is not present.
* `install.sh` also wants to copy `x86_64-linux-haste*`, but `x86_64-darwin-haste-0.5.1.3-ghc-7.10.2`.

**Comment by valderman** [comment]
Thanks for reporting this, I fixed the installer for the OSX package and updated the link on the downloads page. Should be fixed now, please reopen if it's still broken.
