### ISSUE TITLE
Undefined variable in tail call, works correctly with --ddisable-js-opts

### ISSUE THREAD

**Issue by jhp** [valderman/haste-compiler#350]
I'm using version 0.5.2 of the compiler. The code that fails is here: https://github.com/jhp/treersec/blob/master/Treersec.hs#L299

With js optimizations, when I use "x" I get `Uncaught ReferenceError: _C3 is not defined`. `--disable-js-opts` allows the program to run correctly. I also noticed that if I remove the other branches from the case statement, then it works correctly with optimizations, even though it should make no difference semantically.

If you want to reproduce this, you should be able to just download treersec-1 from hackage, remove the --ddisable-js-opts from the cabal file, install it, then use the test file from the README.md. Open the application, click on the "#", and type "x".

**Comment by jhp** [comment]
I just tried this with the latest version from git, but the code doesn't work at all in that case. I'll try to narrow it down.

**Comment by jhp** [comment]
The latest version was causing "ceiling" to behave differently. show (ceiling x), where x is the Double 50, gives "0.0" for some reason. Adding a type annotation fixed the issue. The error I mentioned above is still there though.

**Comment by jhp** [comment]
I think I've been able to reproduce the issue with a simple, standalone file. I just blindly tried to write something with similar features (mutual recursion, let in a case statement).

    import Haste

    main :: IO ()
    main = go


    go = one "abc"
      where
        one xs = case xs of
          'a':xs' -> writeLog "a1" >> two xs'
          'b':xs' -> writeLog "b1" >> two xs'
          'c':xs' -> writeLog "c1" >> two xs'

        two xs = case xs of
          'a':_ -> let xs' = tail xs in writeLog "a2" >> one xs'
          'b':_ -> let xs' = tail xs in writeLog "b2" >> one xs'
          'c':_ -> let xs' = tail xs in writeLog "c2" >> one xs'
          [] -> return ()

**Comment by jhp** [comment]
Here's a shorter example of maybe the same problem.

        import Haste

        main :: IO ()
        main = go


        go = one "abc"
          where
            one xs = case xs of
              'a':xs' -> writeLog "a1" >> two xs'
              'b':xs' -> writeLog "b1" >> two xs'
              'c':xs' -> writeLog "c1" >> two xs'
              [] -> return ()

            two xs = case xs of
              'a':_ -> let xs' = tail xs in writeLog "a2" >> one xs'
              'b':_ -> let xs' = tail xs in writeLog "b2" >> one xs'
              'c':_ -> let xs' = tail xs in writeLog "c2" >> one xs'
              [] -> return ()

**Comment by valderman** [comment]
Thanks for the highly detailed bug report! This program hits a pretty specific optimizer bug: if the latter of two mutually recursive functions does not refer directly to itself and is used *exactly* once outside the first, it will be erroneously inlined.
