### ISSUE TITLE
How can I remove an attribute/property?

### ISSUE THREAD

**Issue by sqd** [valderman/haste-compiler#352]
Same question here http://stackoverflow.com/questions/28339163/how-to-remove-attribute-with-haste

**Comment by valderman** [comment]
Currently there isn't a library function to do this. Expect a fix in the next release. In the meantime, you can use the FFI to implement this yourself:

    unsetAttr :: Elem -> PropID -> IO ()
    unsetAttr = ffi "(function(e, attr) {e.removeAttribute(attr);})"

**Comment by sqd** [comment]
Yes I have figured it out. May I ask why isn't this feature in the library?

**Comment by valderman** [comment]
It's a stupid oversight, really. It should have been there since day one.
