### ISSUE TITLE
Couldn't execute Google Closure compiler

### ISSUE THREAD

**Issue by hotgen** [valderman/haste-compiler#367]
Hi, I have a little problem.

Haste 0.5.4, installed as binaries for Windows.

Then command "hastec --opt-all --opt-minify --output-html 1.hs" stuck forever.
(1.hs is just main = print "a")

When I hit CONTROL-C it prints: "hastec: user error (Couldn't execute Google Closure compiler: Command 'java' failed with error  code 130)"

If run java directly with the same arguments it works as expected:

"java" "-jar" "C:\Program Files\Haste\x86_64-windows-haste-0.5.4-ghc-7.10.2\compiler.jar" "--compilation_level" "ADVANCED_OPTIMIZATIONS" "--jscomp_off" "globalThis" "1.html"
/*
 long.js (c) 2013 Daniel Wirtz <dcode@dcode.io>
 Released under the Apache License, Version 2.0
 see: https://github.com/dcodeIO/long.js for details
*/
function h(a,c){this.w=1;this.D=a;this.I=c}function k(a,c){this.u=a;void 0===c&&(this.x=l)}function n(a,c){this.u=a;this.H=c;..........

**Comment by mateon1** [comment]
I'm having the same problem. I'm on Windows 10 64-bit, and haste hangs while calling the closure compiler. I tried it on a linux machine (ubuntu) and it worked fine.
The `hastec -v` log doesn't show anything useful, it's basically the same with and without --opt-minify except that one without minification finishes.
