### ISSUE TITLE
hastec: Unable to locate function [...] in module GHC.[...]!

### ISSUE THREAD

**Issue by tobi512** [valderman/haste-compiler#368]
Hi Anton, 
hopefully it's not a stupid question, but since I successfully installed and booted Haste (thanks again for the help in #363) I tried to run some of the examples (e.g. calculator) and I'm running into errors of the following type when executing `make` (this one specifically for calculator): 
`hastec: Unable to locate function '$fMonadIO' in module 'GHC.Base'!` 

Any idea what I'm doing wrong, did I misconfigure GHC or sth?! I supposed that the examples should work out of the box and a simple HelloWorld using `main = alert "Hello world!"` works fine...

Thanks in advance!
Tobias

**Comment by valderman** [comment]
This is likely a problem with your workaround for the boot problem: Haste looks for the intermediate code where it placed it, not where that code was later on copied. Does the problem still persist if you use the [prebuild binaries](http://haste-lang.org/downloads) instead (and possibly remove your ~/.haste directory as well, for good measure)?

**Comment by tobi512** [comment]
Wow, that was fast!
Yes you're right, all the stuff seems to be inside the duplicate folder again:
<img width="798" alt="haste-wrong-folder" src="https://cloud.githubusercontent.com/assets/2721729/13081573/9ec3a848-d4cd-11e5-92ab-d4ecdf7b1ba1.png">

I'll try to copy it to the right direction first, since downloading the binaries from haste-lang.org is really slow right now (20 mins left...)

Great support so far, helps me a lot with a university project :+1: 
Greetings from Germany!

**Comment by valderman** [comment]
20 minutes?! I knew the hosting provider was awful, but this is completely unacceptable. Moving to another one, stat.

In the meantime, you can get the binaries from [here](http://shell.ekblad.cc/x/haste-binaries/). It's only a 10 Mb/s line, but it should still be significantly faster than the ~1 MB per minute speeds you're currently seeing from haste-lang.org.

**Comment by tobi512** [comment]
Just 5 more mins now, I can wait :smile: 
Moving the folders worked again, I can successfully compile calculator and it works in the browser, nice!

PS. Are you accepting donations for the project/hosting?

**Comment by valderman** [comment]
Not accepting donations I'm afraid. Not only am I using the same hosting plans for various things, making it a bit sketchy to accept donations earmarked for Haste, but the situation with my employer would also be complicated at best, impossible at worst.
