### ISSUE TITLE
Binary instance for Bool missing

### ISSUE THREAD

**Issue by wilfriedvanasten** [valderman/haste-compiler#369]
I noticed (while deriving Binary instances for my algebraic data types using GHC.Generic) that there is currently no instance of Binary provided for Bool. Is there a reason for this or is this just an oversight?

**Comment by valderman** [comment]
Pure oversight. Will fix before next release.

**Comment by wilfriedvanasten** [comment]
That would be great, thanks!

**Comment by valderman** [comment]
Fixed as of version 0.5.5.1.
