### ISSUE TITLE
Issue installing haste-compiler: Duplicate instance declarations.

### ISSUE THREAD

**Issue by scottmsul** [valderman/haste-compiler#382]
I recently tried installing the haste-compiler on my system using
`cabal install haste-compiler`
But it raised the following errors:

...
[ 7 of 24] Compiling Data.JSTarget.PP ( src/Data/JSTarget/PP.hs, dist/build/hastec/hastec-tmp/Data/JSTarget/PP.o )

src/Data/JSTarget/PP.hs:197:10:
    Duplicate instance declarations:
      instance IsString Builder
        -- Defined at src/Data/JSTarget/PP.hs:197:10
      instance IsString Builder
        -- Defined in `bytestring-builder-0.10.8.1.0:Data.ByteString.Builder'
Failed to install haste-compiler-0.4.3
cabal: Error: some packages failed to install:
haste-compiler-0.4.3 failed during the building phase. The exception was:
ExitFailure 1

Any ideas as to what's causing this? In case it helps, I'm running Ubuntu version 14.04, ghc version 7.6.3, and cabal version 1.16.0.2. I know these aren't fully up-to-date, but they are what comes with APT on Ubuntu.

**Comment by valderman** [comment]
Unfortunately, support for GHC 7.6 was dropped quite some time ago. The only versions of Haste that will work with it are completely outdated by now and, as evidenced by this issue, don't play well with newer libraries.

I'd recommend either getting a more recent GHC version from [Herbert V. Riedel's PPA](https://launchpad.net/~hvr/+archive/ubuntu/ghc) if you really want to install Haste from Hackage or, better yet, install the [pre-built Debian package](http://haste-lang.org/downloads/).

**Comment by valderman** [comment]
Closing this as the 0.4.3 series is no longer supported. If you *really* need to stay on the 0.4 branch, try 0.4.4.4 instead, which should fix this issue.
