### ISSUE TITLE
Prebuilt/pre-booted version on website does not work under OS X

### ISSUE THREAD

**Issue by Hultner** [valderman/haste-compiler#391]
Hi I tried the prebuilt version for OS X from the website (0.5.5.0). Seems like it contains some static links to paths on your file system as I run into the following error if I try to use hastec:
```shell
hastec: user error (shell expression failed in readModule: /Users/valderman/haste-compiler/_build/haste-compiler/haste-compiler/x86_64-darwin-haste-0.5.5.0-ghc-7.10.2/QuickCheck-2.6: getDirectoryContents: does not exist (No such file or directory))
```

I can't use the cabal version as I'm using ghci 8, where it installs but haste-boot doesn't exist.

**Comment by valderman** [comment]
Fixed as of three hours ago. Please try http://haste-lang.org/downloads/ghc-7.10/haste-compiler-0.5.5.1_ghc-7.10.3-darwin.tar.bz2 and reopen if the problem persists.
