### ISSUE TITLE
Question: Does haste support passing (variadic) callbacks to javascript?

### ISSUE THREAD

**Issue by crocket** [valderman/haste-compiler#393]
A while ago, to ghcjs-base project, I submitted a pull request that adds variadic callback generators. You can read the details on https://github.com/crocket/ghcjs-base#callbacks-with-arbitrary-numbers-of-arguments.

Haste seems similar to GHCJS, and I wonder whether I can do the same with Haste.

**Comment by valderman** [comment]
Haste supports passing callbacks through the `Haste.Foreign` FFI:

    {-# LANGUAGE OverloadedStrings #-}
    import Haste.Foreign

    withPrompt :: (String -> IO ()) -> IO ()
    withPrompt = ffi "(function(f){f(prompt('Name, please!'));})"

    main = withPrompt $ \name -> putStrLn ("Hello, " ++ name)

While it doesn't support functions which are actually variadic (i.e. may be called with a different number of arguments each time), you can easily fake it using `Maybe` arguments (currently only in 0.6 dev branch; 0.5.x doesn't consider `undefined` to be `Nothing` for marshalling purposes):

    {-# LANGUAGE OverloadedStrings #-}
    import Haste.Foreign

    withPrompt :: (Maybe String -> IO ()) -> IO ()
    withPrompt = ffi "(function(f){f();})"

    main = withPrompt $ \mname -> do
      case mname of
        Just name -> putStrLn ("Hello, " ++ name)
        _         -> putStrLn "No name. :("

[This paper](http://haste-lang.org/pubs/ifl15.pdf) describes the FFI in detail. There isn't a lot of user-oriented documentation for the FFI in particular, but [this example](https://github.com/valderman/haste-compiler/blob/master/examples/ffi/ffi.hs) shows the basics through a very minimal jQuery example.

**Comment by crocket** [comment]
It seems Haste FFI overlaps with GHCJS FFI and ghcjs-base.

I mixed `arguments` object with a variadic function to create variadic callback generators. They do not create variadic callbacks, but they can create any kind of callback. =

If it was possible to convert a haskell function to a javascript function, the same trick as I used in ghcjs-base could be used.

**Comment by valderman** [comment]
With Haste any Haskell function can be used as a callback, without having to call an explicit generator for it. If you want to do that anyway for some reason, you can just use the `ToAny` instance for marshallable functions: `some_callback = toAny $ \x y z -> putStrLn (concat [x, y, z])`.

As far as I understand, your variadic generator essentially allows the same thing but for the JSFFI, which is more restrictive about what values can be marshalled? If I'm mistaken here, could you give an example of a Haste program that would benefit from having this construction, to help me understand the idea a bit better?

Apologies for the late reply; things have been a bit hectic of late.

**Comment by crocket** [comment]
If any haskell function can be used as a callback in haste, then haste doesn't need my callback generator. GHCJS FFI is not very good.
