### ISSUE TITLE
--no-haste-cabal option no longer exists for haste-boot

### ISSUE THREAD

**Issue by gwildr** [valderman/haste-compiler#394]
I'm trying to build and boot Haste according the instructions on the build page [https://github.com/valderman/haste-compiler/blob/master/doc/building.md](url).

I've completed the instructions up until Booting Haste.
Since I have built haste-cabal I want to tell haste-boot to avoid downloading a pre-built haste-cabal binary using the --no-haste-cabal flag. 

But this flag doesn't seem to exist anymore.

The options I get when I run `haste-boot --help` are the following:

`--dev
  Boot Haste for development. Implies --force --local --no-closure
  --build-haste-cabal

--force
  Re-boot Haste even if already properly booted.

--initial
  Prepare boot files for binary distribution. Should only ever be called by the
  release build scripts, never by users. Implies --local --force.

--local
  Use libraries from source repository rather than downloading a matching set
  from the Internet. This is nearly always necessary when installing Haste from
  Git rather than from Hackage. When using --local, your current working
  directory must be the root of the Haste source tree.

--no-closure
  Don't download Closure compiler. You won't be able to use --opt-minify,
  unless you manually give hastec the path to compiler.jar.

--download-haste-cabal
  Download pre-built haste-cabal for your platform. This is the default
  behaviour.

--with-haste-cabal=FILE
  Use FILE to provide haste-cabal.

--build-haste-cabal[=DIR]
  Build haste-cabal from the source contained in DIR. If DIR is not specified,
  `../cabal/' is assumed.

--no-libs
  Don't install any libraries. This is probably not what you want.

--trace-primops
  Build standard libs for tracing of primitive operations. Only use if you're
  debugging the code generator.

-v, --verbose
  Print absolutely everything.`

**Comment by valderman** [comment]
`--no-haste-cabal` got replaced with `--with-haste-cabal=$YOUR_BINARY`, which ensures that `$YOUR_BINARY` is both used to boot Haste, and installed together with the other binaries.
