### ISSUE TITLE
Official binaries of 0.5.5.1

### ISSUE THREAD

**Issue by perglr** [valderman/haste-compiler#415]
Can you please make links to the binaries in the release section, as is with 0.6.0.0? (Currently, just source code is available) Thanks!

**Comment by valderman** [comment]
Up until 0.5.5.1 the binaries were hosted directly from haste-lang.org. They're still available from the [7.10-based older versions link](https://haste-lang.org/downloads/ghc-7.10/).

I also added a [0.5.5.1 release](https://github.com/valderman/haste-compiler/releases/tag/0.5.5.1) here for convenience.
