### ISSUE TITLE
Support for `impl(haste)` in `.cabal` files

### ISSUE THREAD

**Issue by nomeata** [valderman/haste-compiler#64]
Some library authors might want to have different settings in their cabal file for compilation with haste. In theory, cabal supports that via the `impl` conditional (see [the docs](http://www.haskell.org/cabal/users-guide/developing-packages.html#conditions) for details), but it seems that with `haste-inst`, `impl(ghc)` is true and `impl(haste)` is false. (This bug report was initated by [this stackoverflow question](http://stackoverflow.com/questions/17619827/replace-compiler-when-building-haskell-project-with-cabal).)

**Comment by valderman** [comment]
Fixed by new `haste-cabal` on master. Will look into getting these changes into upstream cabal after Haste support has had some time to mature.
